config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  resources :toppages, only: [:show]

  resources :users, only: [:show, :create, :edit, :update, :destroy, :destroy_confirm] do
   member do
     get :likes
   end
  end
  # post 'users/confirm', to: 'users#confirm'
  # patch 'users/edit/confirm/:id', to: 'users#edit_confirm'
  get 'users/delete/confirm/:id', to: 'users#destroy_confirm'
  
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :contracts, only: [:index, :create, :destroy, :update]
  # patch 'contracts/edit/confirm/:id', to: 'contracts#edit_confirm'
  
  resources :claims, only: [:new, :create, :destroy]
  get 'claims_list', to: 'claims#claims_list'
  
  namespace :admin do
    resources :info,only: [:show, :edit, :update]
    # patch 'info/edit/confirm/:id', to: 'info#edit_confirm'
  end
  
  resources :posts, only: [:new, :create, :index, :show, :destroy]
  # get 'posts/delete/confirm/:id', to: 'posts#destroy_confirm'

  resources :likes, only: [:create, :destroy, :index]
  
  resources :guest_sessions, only: [:create]
  
  resources :contacts, only: [:index, :create, :destroy]
  
  resources :comments, only: [:index, :create, :destroy]
  get 'comments/:id', to: 'comments#show'

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :contact
  validates :content, presence: true, length: { maximum: 300 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user_logged_in
  before_action :if_not_admin, only: [:index]
  # admin以外はユーザー認証必須とする
  before_action :correct_user, only: [:show], if: proc{ current_user.email != "admin@admin.com" } 
  
  def index
    @contacts = Contact.order(created_at: :desc).page(params[:page]).per(5)
  end

  def show
    @contact = Contact.find(params[:id])
    @comment = @contact.comments.build
    @comment.user_id = current_user.id
    @comments = @contact.comments.order(id: :desc).page(params[:page]).per(3)
  end

  def create
    @contact = Contact.find(params[:contact_id])
    @comment = @contact.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comments = @contact.comments.order(id: :desc).page(params[:page]).per(3)
    if @comment.save
      @msg = "返信しました"
    else
      @msgs = @comment.errors.full_messages.join("、")
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    @msg = "#{@comment.created_at.to_s(:datetime_jp)}に送信した返信を削除しました"
  end
  
  private
 
  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end
  
  def comment_params
    params.require(:comment).permit(:content)
  end
  
  def correct_user
    @contact = current_user.contacts.find_by(id: params[:id])
    if @contact
    else
    redirect_to "/"
    end
  end
  
end

app/views/comments/_u_comment.html.erb
<!--返信一覧パーシャル-->
<!--フラッシュmsg-->
<div id="comment_msg"></div>
<%# @contact.comments.each do |comment| %>
<% @comments.each do |comment| %>
  <!--データブランクがあるものは非表示-->
    <% unless comment.blank? %>
     <!--destroy.jsで削除するID-->
      <div id="comment-<%= comment.id %>" >
        <table class="table comment_table fix_table" >
          <tr>
            <th colspan="2" class="text-center align-middle table-warning c_font_color <%= "a_color" if comment.user.contractor_name == "管理者" %>">
              <div class="cm_header_item">
                <%= comment.user.contractor_name %>
                <!--ログインユーザー名と返信者が一致する場合に削除を表示-->
                <% if current_user.contractor_name == comment.user.contractor_name %>
                  <div class="cm_icon_item">
                    <%= link_to comment, method: :delete, data: { confirm: "削除しますか？" }, remote: true do %>
                      <span id="e_icon" class="font_color_red" ><i class="fas fa-trash-alt"></i></span>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </th>
          </tr>
          <tr>
            <th width="20%" class="users_th text-center align-middle c_font_color">返信日</th>
            <th class="text-center align-middle"><%= comment.created_at.to_s(:datetime_jp) %></th>
          </tr>
          <tr>
            <th width="20%" class="users_th text-center align-middle c_font_color">内容</th>
            <th class="align-middle"><%= safe_join(comment.content.split("\n"),tag(:br)) %></th>
          </tr>
        </table>
      </div>
    <% end %>
<% end %>
<div class="pagination  justify-content-center">
  <%= paginate @comments %> 
</div>
    
    

app/views/comments/create.js.erb
<% if @comment.save %>
  $("#u_comments").html("<%= j(render partial: 'comments/u_comment') %>");
  $("textarea").val('');
  $("#comment_msg").html('<div style="color:green; margin-bottom:10px;"><%= @msg %></div>');
  $("#new_msg").html('');
<% else %>
  $("#new_msg").html('<div style="color:red; margin-bottom:10px;"><%= @msgs %></div>');
<% end %>

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').html('');
$('#comment_msg').html('<div style="color:red; margin-bottom:10px;"><%= @msg %></div>');

app/views/comments/index.html.erb
<div class="ad_wrapper">
  <div class="ad_visual" >
    <div class="ad_container">
      <h1>お問い合わせ一覧</h1>
    </div>
  </div>
  <p>加入者からのお問い合わせを確認の上、返信ください。</p>
  <% if @contacts.any? %>
    <% @contacts.each do |contact| %>
      <div class="col-md-8 offset-md-2 mt-5 mb-5">
        <span>お問い合わせID:<%= contact.id %></span>
        <table class="table">
          <tr>
            <th width="40%" class="text-center a_font_color">お問い合わせ日</th>
            <th width="40%" class="text-center a_font_color">お問い合わせ種類</th>
            <th width="20%" class="text-center a_font_color">−</th>
          </tr>
          <tr>
            <th style="background-color:white;" class="text-center"><%= contact.created_at.to_s(:datetime_jp) %></th>
          　<th style="background-color:white;" class="text-center"><%= contact.type %></th>
          　<th style="background-color:white;" rowspan=”2 class="text-center"><%= link_to "返信する", comment_path(contact.id), class: "font_color" %></th>
          </tr>
        </table>
      </div>
     <% end %>
  <% else %>
    <p class="contract_nill">お問い合わせがありません。</p>
  <% end %>
  <div class="pagination  justify-content-center">
    <%= paginate @contacts %>
  </div>
  <div class="main_btn">
    <%= link_to "戻る", "/",class: "return_btn" %>
  </div>
</div>


 

app/views/comments/show.html.erb
<!--do us共通画面につき画面分岐-->
<div class="us_wrapper">
  <div class=<%= "ad_visual" if logged_in? && current_user.admin?  %>
           <%= "us_visual" if logged_in?  %>>
    <div class="us_container">
      <h1>お問い合わせの詳細</h1>
    </div>
  </div>
  <p>お問い合わせおよび返信内容をご確認し、適宜、ご返信ください。</p>
  <div class="row justify-content-md-center ml-5 mr-5 mb-3 mb-3">
  <!--お問い合わせ-->
    <div class="col-md-5">
      <h2 class="comment_h2">お問い合わせ内容</h2>
      <table class="table comment_table">
        <tr>
          <th colspan="2" class="text-center align-middle c_font_color table-secondary">
            <div class="cm_header_item">
              お問い合わせID: <%= @contact.id %>
              <!--ログインユーザー名と返信者が一致する場合に削除を表示-->
              <% unless current_user.admin? %>
              <div class="cm_icon_item">
                <%= link_to @contact, method: :delete, data: { confirm: "返信内容も全て削除されますがよろしいですか？" } do %>
                  <span id="e_icon" class="font_color_red" ><i class="fas fa-trash-alt"></i></span>
                <% end %>
              </div>
              <% end %>
            </div>
          </th>
        </tr>
        <tr>
          <th class="text-left align-middle c_font_color">お問い合わせ日</th>
          <th class="text-center align-middle"><%= @contact.created_at.to_s(:datetime_jp) %></th>
        </tr>
        <tr>
          <th class="text-left align-middle c_font_color">送信者</th>
          <th class="text-center align-middle"><%= @contact.user.contractor_name %></t>
        </tr>
        <tr>
          <th class="text-left align-middle c_font_color">お問い合わせ種類</th>
          <th class="text-center align-middle"><%= @contact.type %></t>
        </tr>
        <tr>
          <th class="text-left align-middle c_font_color">件名</th>
          <th class="text-center align-middle"><%= @contact.title %></th>
        </tr>
        <tr>
          <th class="text-left align-middle c_font_color">お問い合わせ内容</th>
          <th class="align-left align-middle"><%= safe_join(@contact.content.split("\n"),tag(:br)) %></th>
        </tr>
      </table>
      <!--返信フォーム-->
      <h2 class="comment_h2">返信フォーム</h2>
        <div class="form">
          <%= form_with(model: @comment, id: 'comment_form') do |f| %>
          <%= hidden_field_tag :contact_id, @contact.id  %>
          <!--フラッシュ、バリデーションmsg-->
          <p id="new_msg" style="padding-top: 0px; margin-bottom: 0px; font-size: 18px;"></p>
          <table class="table table-bordered table-md mt-3 table-success">
            <tr>
              <td>
                <h6 style="color:red; font-size:13px;">※300字以内でご入力ください。</h6>
                <div class="count_area"><span class="now_count">0</span> / 300</div>
                <%= f.text_area :content,:size => "60x6", class: 'form-control ajax_text', id: 't_count' %>
              </td>
            </tr>
            <tr>
              <td colspan="2" class="text-center align-middle"><%= f.submit '返信', class: 'next_btn' %></td>
            </tr>
          </table>
          <% end %>
        </div>
      </div>
    <!--返信表示-->
    <div class="col-md-5">
      <h2 class="comment_h2" >返信一覧</h2>
      <div id="u_comments">
        <%= render "comments/u_comment" %>
      </div>
    </div>
  </div>
    <div class="main_btn">
     <% if logged_in? && current_user.admin? %>
      <%= link_to "戻る", comments_path,class: "return_btn" %>
     <% else %>
      <%= link_to "戻る", contacts_path,class: "return_btn" %>
     <% end %>
    </div>
</div> 