config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  resources :toppages, only: [:show]

  resources :users, only: [:show, :create, :edit, :update, :destroy, :destroy_confirm] do
   member do
     get :likes
   end
  end
  # post 'users/confirm', to: 'users#confirm'
  # patch 'users/edit/confirm/:id', to: 'users#edit_confirm'
  get 'users/delete/confirm/:id', to: 'users#destroy_confirm'
  
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :contracts, only: [:index, :create, :destroy, :update]
  # patch 'contracts/edit/confirm/:id', to: 'contracts#edit_confirm'
  
  resources :claims, only: [:new, :create, :destroy]
  get 'claims_list', to: 'claims#claims_list'
  
  namespace :admin do
    resources :info,only: [:show, :edit, :update]
    # patch 'info/edit/confirm/:id', to: 'info#edit_confirm'
  end
  
  resources :posts, only: [:new, :create, :index, :show, :destroy]
  # get 'posts/delete/confirm/:id', to: 'posts#destroy_confirm'

  resources :likes, only: [:create, :destroy, :index]
  
  resources :guest_sessions, only: [:create]
  
  resources :contacts, only: [:index, :create, :destroy]
  
  resources :comments, only: [:index, :create, :destroy]
  get 'comments/:id', to: 'comments#show'

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  
  def index
    @posts = Post.order(id: :desc)
    @user = User.new
  end

  def show
    @post = Post.find(params[:id])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:contractor_name, :email, :address, :password)
  end
  
end

app/views/toppages/_admin_login_modal.html.erb
<div class="login_modal_wrapper" id='admin_login_modal'>
  <div class="row justify-content-center">
    <div class="login_modal col-md-4 pr-10 pl-10">
      <!--閉じる-->
      <div class="close-modal">
        <i class="fas fa-times-circle fa-2x"></i>
      </div>
      <!--入力フォーム-->
      <h1>管理者ログイン</h1>
      <p style="color: red" >ポートフォリオ用として入力値を初期表示しています。</p>
      <%= form_with(url: login_path, scope: :session) do |f| %>
        <div class="form-group">
          <%= f.email_field :email, class: 'form-control',value: "admin@admin.com", readonly:true %>
        </div>
        <div class="form-group">
          <%= f.password_field :password, class: 'form-control',value: "a", readonly:true %>
        </div>
        <div class="main_btn">
          <%= f.submit '管理者ログイン', class: 'next_btn' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/toppages/_admin_message.html.erb
<!--機能説明-->
<div class="message-wrapper animated">
  <div class="message_container">
    <div class="heading">
      <h2>管理者画面でできること</h2>
    </div>
    <div class="row">
 <!--各機能説明     -->
      <div class="col-md-4">
        <div class="message">
          <div class="fas_text">
            <i class="fas fa-ad fa-4x fa_ad_color"></i>
          </div>
          <h2>保険商品PR記事の投稿</h2>
          <div class="output1 txt-contents">
            <p>保険商品のPR記事を投稿することができます。投稿した記事はトップページに表示されます。</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="message">
          <div class="fas_text">
           <i class="fas fa-file-csv fa-4x fa_ad_color"></i>
          </div>
          <h2>CSV出力</h2>
          <div class="output2 txt-contents">
            <p>ご契約者からの給付金請求を確認することでき、請求データのCSV出力を行うことができます。</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="message">
          <div class="fas_text">
            <i class="fas fa-check-circle fa-4x fa_ad_color"></i>
          </div>
          <h2>各種お問い合わせ対応</h2>
          <div class="output3 txt-contents">
            <p>ご契約者からの資料請求やお問い合わせへ、非同期通信にて返信を繰り返し行うことができます。</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--商品紹介-->
<div class="likes-wrapper animated">
  <div class="heading">
    <h2>投稿した記事</h2>
  </div>
  <div class="likes">
    <% @posts.each do |post| %>
      <%= link_to(toppage_path(post.id)) do %>
        <ul>
          <table class="table_toppage table-bordered">
            <tr>
               <th class="text-center"><%= post.title %></th>
            </tr>
            <tr>
               <th class="text-center"><%= attachment_image_tag post, :post_img, :size =>'250x250', :style => "border-radius: 30%" %></th>
            </tr>
            <tr>
               <% if current_user.present? %>
               <th class="text-center"><%= link_to "詳細/お気に入り登録", toppage_path(post.id), class: "font_color" %></th>
               <% else %>
               <th class="text-center"><%= link_to "詳細", toppage_path(post.id), class: "font_color" %></th>
               <% end %>
            </tr>
          </table>
        </ul>
        <% end %>
    　<% end %>
  </div>
</div>

app/views/toppages/_guest_modal.html.erb
<div class="login_modal_wrapper" id='guest_modal'>
  <div class="row justify-content-center">
    <div class="login_modal col-md-4 pr-10 pl-10">
      <!--閉じる-->
      <div class="close-modal">
        <i class="fas fa-times-circle fa-2x"></i>
      </div>
      <!--リード文-->
      <h1>ゲストログイン</h1>
      <p>お試しユーザーとしてログインします。<br>本登録される場合は「新規登録」より、ご登録をお願いします。</p>
      <%= link_to 'ゲストログイン', guest_sessions_path,class: "next_btn",method: :post %>
    </div>
  </div>
</div>

        

app/views/toppages/_login_modal.html.erb
<div class="login_modal_wrapper" id='login_modal'>
  <div class="row justify-content-center">
    <div class="login_modal col-md-4 pr-10 pl-10">
      <!--閉じる-->
      <div class="close-modal">
        <i class="fas fa-times-circle fa-2x"></i>
      </div>
      <!--入力フォーム-->
      <h1>ユーザーログイン</h1>
      <%= form_with(url: login_path, scope: :session) do |f| %>
        <!--失敗時のフラッシュmsg-->
        <div id="errors_login"></div>
        <div class="form-group">
          <%= f.email_field :email, class: 'form-control',placeholder: "メール"%>
        </div>
        <div class="form-group">
          <%= f.password_field :password, class: 'form-control',placeholder: "パスワード" %>
        </div>
        <div class="main_btn">
          <%= f.submit 'ユーザーログイン', class: 'next_btn' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/toppages/_new_modal.html.erb
<div class="login_modal_wrapper" id='new_modal'>
  <div class="row justify-content-center">
    <div class="login_modal col-md-6" style="height: 70% !important;">
      
      <!--閉じる-->
      <div class="close-modal">
        <i class="fas fa-times-circle fa-2x"></i>
      </div>
      <h1>新規登録</h1>
      <!--入力フォーム-->
      <%= form_with(model: @user ) do |f| %>
      <div style="padding: 0 5%;">
        <!--バリデーションエラー-->
        <div id="errors_new">
        </div>
        <div class="form-group text-left">
          <%= f.label :contractor_name %>
          <%= f.text_field :contractor_name, class: 'form-control new_text1'%>
        </div>
        <div class="form-group text-left">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control new_text2' %>
        </div>
        <!--住所検索API-->
        <div class="form-group text-left">
          <%= f.label :address%>
          <h6 style="color:red; font-size:13px;">※住所検索は半角数字、ハイフンなしでご入力ください。</h6>
          <div class="row">
            <div class="form-group input-group col-sm-4">
              <div class="input-group-prepend">
                <span class="input-group-text">〒</span>
              </div>
                <input id="zip-code" type="number" class="form-control" placeholder="住所検索">
            </div>
            <div class="form-group col-sm-8">
              <%= f.text_field :address, class: 'form-control place'%>
            </div>
          </div>     
        </div>
        <div class="form-group text-left">
          <%= f.label :"パスワード" %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group text-left">
          <%= f.label :"パスワード再確認" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <div class="main_btn">
          <%= f.submit '登録', class: 'next_btn', data: { confirm: "登録しますか？" } %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/toppages/_no_message.html.erb
<!--機能説明-->
<div class="message-wrapper animated">
  <div class="message_container">
    <div class="heading">
      <h2>ご契約者専用サイトの利用について</h2>
    </div>
 <!--各機能説明-->
    <!--user機能説明-->
    <h3>ご契約者様</h3>
    <div class="row justify-content-md-center mr-5 ml-5">
      <div class="col-md-3">
        <div class="message">
          <div class="fas_text">
            <i class="fas fa-address-card fa-4x       
            <%= "fa_us_color" if logged_in?  %>
            <%= "fa_no_color" unless logged_in?  %>"></i>
          </div>
          <h2>ご加入契約の登録</h2>
          <div class="output1 txt-contents">
            <p>ご加入契約のご登録ができ、ご加入契約での入院給付金のご請求やご加入契約の確認ができます。</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="message">
          <div class="fas_text">
            <i class="fas fa-calculator fa-4x       
            <%= "fa_us_color" if logged_in?  %>
            <%= "fa_no_color" unless logged_in?  %>"></i>
          </div>
          <h2>請求のお手続き</h2>
          <div class="output2 txt-contents">
            <p>窓口に起こし頂かなくとも、当サイトより入院給付金のご請求ができます。</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="message">
          <div class="fas_text">
            <i class="fas fa-envelope fa-4x       
            <%= "fa_us_color" if logged_in?  %>
            <%= "fa_no_color" unless logged_in?  %>"></i>
          </div>
          <h2>各種お問い合わせ</h2>
          <div class="output3 txt-contents">
            <p>当サイトより資料請求や給付金請求に関するお問い合わせができます。</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="message">
          <div class="fas_text">
            <i class="fas fa-thumbs-up fa-4x       
            <%= "fa_us_color" if logged_in?  %>
            <%= "fa_no_color" unless logged_in?  %>"></i>
          </div>
          <h2>お気に入り</h2>
          <!--IDはページ内リンク用-->
          <div class="output4 txt-contents" id="link2">
            <p>気になる保険商品をお気に入り登録できます。</p>
          </div>
        </div>
      </div>
    </div>
    <!--admin機能説明-->
    <h3>管理者様</h3>
    <div class="row justify-content-md-center  mr-5 ml-5">
      <div class="col-md-4">
        <div class="message">
          <div class="fas_text">
            <i class="fas fa-ad fa-4x fa_ad_color"></i>
          </div>
          <h2>保険商品PR記事の投稿</h2>
          <div class="output1 txt-contents">
            <p>保険商品のPR記事を投稿することができます。投稿した記事はトップページに表示されます。</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="message">
          <div class="fas_text">
           <i class="fas fa-file-csv fa-4x fa_ad_color"></i>
          </div>
          <h2>CSV出力</h2>
          <div class="output2 txt-contents">
            <p>ご契約者からの給付金請求を確認することでき、請求データのCSV出力を行うことができます。</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="message">
          <div class="fas_text">
            <i class="fas fa-check-circle fa-4x fa_ad_color"></i>
          </div>
          <h2>各種お問い合わせ対応</h2>
          <div class="output3 txt-contents">
            <p>ご契約者からの資料請求やお問い合わせに対して返信を繰り返し行うことができます。</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--商品紹介-->
<div class="<%= "likes-wrapper_no" unless logged_in?  %>
            <%= "likes-wrapper_us" if logged_in?  %> animated">
  <div class="heading">
    <h2>生命保険をご検討の方</h2>
  </div>
  <div class="likes">
    <% @posts.each do |post| %>
      <%= link_to(toppage_path(post.id)) do %>
        <ul>
          <table class="table_toppage table-bordered">
            <tr>
               <th class="text-center"><%= post.title %></th>
            </tr>
            <tr>
               <th class="text-center"><%= attachment_image_tag post, :post_img, :size =>'250x250', :style => "border-radius: 30%" %></th>
            </tr>
            <tr>
               <% if current_user.present? %>
               <th class="text-center"><%= link_to "詳細/お気に入り登録", toppage_path(post.id), class: "font_color" %></th>
               <% else %>
               <th class="text-center"><%= link_to "詳細", toppage_path(post.id), class: "font_color" %></th>
               <% end %>
            </tr>
          </table>
        </ul>
        <% end %>
    　<% end %>
  </div>
</div>
<!--FQQ-->
<!--IDはページ内リンク用-->
<div class="faq-wrapper animated" id="link3">
  <div class="faq-container">
    <div class="heading">
      <h2>よくある質問</h2>
    </div>
    <div class="faq">
      <ul class="faq-list">
        <li class="faq-list-item" >
          <h3 class="question"><i class="fab fa-quora"></i>  加入済みの契約を登録する場合、何を参照すればよいですか。</h3>
          <span>+</span>
          <div class="answer">
            <p>お手持ちの保険証書をご確認の上、契約の新規登録を行ってください。</p>
          </div>
        </li>
        <li class="faq-list-item" >
          <h3 class="question"><i class="fab fa-quora"></i>  給付金の請求を取消したいのですが、どうすればよいでしょうか。</h3>
          <span>+</span>
          <div class="answer">
            <p>基本的に給付金の請求取消はできませんが、特別な事情がある場合はTelxxx-xxx-xxxまでご連絡ください。弊社にて取消いたします。</p>
          </div>
        </li>
        <li class="faq-list-item" >
          <h3 class="question"><i class="fab fa-quora"></i>  保険契約を解約したのでマイページも退会したいです。</h3>
          <span>+</span>
          <div class="answer">
            <p>「ご契約者様情報」より退会手続きを行ってください。</p>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/toppages/_user_message.html.erb
<!--機能説明-->
<div class="message-wrapper animated">
  <div class="message_container">
    <div class="heading">
      <h2>ご契約者専用サイトの利用について</h2>
    </div>
    <div class="row">
 <!--各機能説明     -->
      <div class="col-md-3">
        <div class="message">
          <div class="fas_text">
            <i class="fas fa-address-card fa-4x       
            <%= "fa_us_color" if logged_in?  %>
            <%= "fa_no_color" unless logged_in?  %>"></i>
          </div>
          <h2>ご加入契約の登録</h2>
          <div class="output1 txt-contents">
            <p>ご加入契約のご登録ができ、ご加入契約での入院給付金のご請求やご加入契約の確認ができます。</p>
          </div>
        </div>
      </div>
      
      <div class="col-md-3">
        <div class="message">
          <div class="fas_text">
            <i class="fas fa-calculator fa-4x       
            <%= "fa_us_color" if logged_in?  %>
            <%= "fa_no_color" unless logged_in?  %>"></i>
          </div>
          <h2>請求のお手続き</h2>
          <div class="output2 txt-contents">
            <p>窓口に起こし頂かなくとも、当サイトより入院給付金のご請求ができます。</p>
          </div>
        </div>
      </div>
      
      <div class="col-md-3">
        <div class="message">
          <div class="fas_text">
            <i class="fas fa-envelope fa-4x       
            <%= "fa_us_color" if logged_in?  %>
            <%= "fa_no_color" unless logged_in?  %>"></i>
          </div>
          <h2>各種お問い合わせ</h2>
          <div class="output3 txt-contents">
            <p>当サイトより資料請求、給付金請求に関するお問い合わせができます。</p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="message">
          <div class="fas_text">
            <i class="fas fa-thumbs-up fa-4x       
            <%= "fa_us_color" if logged_in?  %>
            <%= "fa_no_color" unless logged_in?  %>"></i>
          </div>
          <h2>お気に入り</h2>
          <!--IDはページ内リンク用-->
          <div class="output4 txt-contents" id="link2">
            <p>気になる保険商品をお気に入り登録できます。</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--商品紹介-->
<div class="<%= "likes-wrapper_no" unless logged_in?  %>
            <%= "likes-wrapper_us" if logged_in?  %> animated">
  <div class="heading">
    <h2>生命保険をご検討の方</h2>
  </div>
  <div class="likes">
    <% @posts.each do |post| %>
      <%= link_to(toppage_path(post.id)) do %>
        <ul>
          <table class="table_toppage table-bordered">
            <tr>
               <th class="text-center"><%= post.title %></th>
            </tr>
            <tr>
               <th class="text-center"><%= attachment_image_tag post, :post_img, :size =>'250x250', :style => "border-radius: 30%" %></th>
            </tr>
            <tr>
               <% if current_user.present? %>
               <th class="text-center"><%= link_to "詳細/お気に入り登録", toppage_path(post.id), class: "font_color" %></th>
               <% else %>
               <th class="text-center"><%= link_to "詳細", toppage_path(post.id), class: "font_color" %></th>
               <% end %>
            </tr>
          </table>
        </ul>
        <% end %>
    　<% end %>
  </div>
</div>
<!--FQQ-->
<!--IDはページ内リンク用-->
<div class="faq-wrapper animated" id="link3">
  <div class="faq-container">
    <div class="heading">
      <h2>よくある質問</h2>
    </div>
    <div class="faq">
      <ul class="faq-list">
        <li class="faq-list-item" >
          <h3 class="question"><i class="fab fa-quora"></i>  加入済みの契約を登録する場合、何を参照すればよいですか。</h3>
          <span>+</span>
          <div class="answer">
            <p>お手持ちの保険証書をご確認の上、契約の新規登録を行ってください。</p>
          </div>
        </li>
        <li class="faq-list-item" >
          <h3 class="question"><i class="fab fa-quora"></i>  給付金の請求を取消したいのですが、どうすればよいでしょうか。</h3>
          <span>+</span>
          <div class="answer">
            <p>基本的に給付金の請求取消はできませんが、特別な事情がある場合はTelxxx-xxx-xxxまでご連絡ください。弊社にて取消いたします。</p>
          </div>
        </li>
        <li class="faq-list-item" >
          <h3 class="question"><i class="fab fa-quora"></i>  保険契約を解約したのでマイページも退会したいです。</h3>
          <span>+</span>
          <div class="answer">
            <p>「ご契約者様情報」より退会手続きを行ってください。</p>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/toppages/index.html.erb
<!--画像分岐-->
<div class=<%= "a_main_visual" if logged_in? && current_user.admin?  %>
           <%= "u_main_visual" if logged_in?  %>
           <%= "main_visual" unless logged_in?  %>>
  <div class="main_container">
    <% unless logged_in? %>
      <h1>筋肉生命の<br>ご契約者専用アプリへようこそ！</h1>
    <% else %>
      <h1>ようこそ！<br><%= current_user.contractor_name %>さん！</h1>
    <% end %>
  </div>
<!--IDはページ内偏移用-->
  <div class="btn_wrapper" id="link1">
    <div class="col-xs-12 col-md-8 offset-md-2">
      <div class="main_btn">
        <% unless logged_in? %>
          <div class="sinup_btn guest_show">ゲストログイン</div>
          <div class="sinup_btn login_show">ユーザーログイン</div>
          <div class="sinup_btn admin_login_show">管理者ログイン</div>
          <div class="sinup_btn new_show">新規登録</div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!--モーダル-->
<%= render "login_modal" %>
<%= render "guest_modal" %>
<%= render "admin_login_modal" %>
<%= render "new_modal" %>
<!--hover message-->
<% if logged_in? && current_user.admin? %>
  <%= render "admin_message" %>
<% elsif logged_in? %>
  <%= render "user_message" %>
<% else %>
  <%= render "no_message" %>
<% end %>

app/views/toppages/show.html.erb
<!--do us共通画面につき画面分岐-->
<div class="us_wrapper">
  <div class=<%= "ad_visual" if logged_in? && current_user.admin?  %>
           <%= "us_visual" if logged_in?  %>
           <%= "ma_visual" unless logged_in?  %>>
    <div class="us_container">
      <h1>保険商品の詳細</h1>
    </div>
  </div>
  <!--資料請求案内。ログインしていればお問い合わせ、そうでなければ電話番号案内-->
  <% if current_user.present? %>
    <div class="fas_text">
      <i class="fas fa-file-signature"></i>
      資料請求、ご相談（無料）は<%= link_to 'お問い合わせ',contacts_path, class: "font_color" %>まで！
    </div>
  <% else %>
    <div class="fas_text">
      <i class="fas fa-phone"></i>
      資料請求、ご相談（無料）はxxx-xxx-xxxまで！
    </div>
  <% end %>
  
  <div class="offset-2 col-8 offset-2 mt-3 mb-5 like_table">
    <table class="table fix_table">
      <tr>
        <th colspan="2" class="text-center like_th" style="color: #000000;"><%= @post.title %></th>
      </tr>
      <tr>
        <td width=50% class="text-center align-middle like_td"><%= attachment_image_tag @post, :post_img, :size =>'300x300', class: "like_size" %></td>
        <td width=50% class="text-left align-middle like_td"><%= safe_join(@post.content.split("\n"),tag(:br)) %></td>
      </tr>
      <% if current_user.present? %>
      <tr>
        <th colspan="2" class="like_td">
          <div id="likes_buttons_<%= @post.id %>" class="text-center">
            <% if current_user.likeing?(@post) %>
              <%= form_with(model: current_user.likes.find_by(post_id: @post.id), method: :delete) do |f| %>
                <%= hidden_field_tag :post_id ,@post.id %>
                <%= f.submit 'お気に入りを解除',class: "unlike_btn" %>
              <% end %>
            <% else %>
              <%= form_with(model: current_user.likes.build) do |f| %>
                <%= hidden_field_tag :post_id, @post.id %>
                <%= f.submit 'お気に入り登録',class: "like_btn" %>
              <% end %>
            <% end %>
          </div>
        </th>
      </tr>
      <% end %>
    </table>
  </div>
  <div class="main_btn">
    <%= link_to '戻る',root_path,class: "return_btn" %>
  </div>
</div>


<%
=begin
%>
    <!--<div class="like_title"><%#= @post.title %></div>-->
    <!--    <table class="table table-bordered table-sm table-success ">-->
    <!--      <tr>-->
    <!--        <div class="row">-->
    <!--          <th  class="text-center align-middle"><%#= @post.content %></th>-->
    <!--          <td class="text-center align-middle"><%#= attachment_image_tag @post, :post_img, :size =>'300x300' %></td>-->
    <!--        </div>-->
    <!--      </tr>-->
    <!--    </table>-->
    <!--</div>-->

<!--<div id="like_msg"></div>-->
<!--<div class="main_btn">-->
  <!--ログインしていなければ「戻る」ボタンのみ表示  -->
<!--  <% if current_user.present? %>-->
<!--  <div class="row justify-content-center">-->
<!--    <div class="col-md-3">-->
<!--      <%= link_to '戻る',root_path,class: "return_btn" %>-->
<!--    </div>-->
<!--    <div id="likes_buttons_<%= @post.id %>" class="col-md-3">-->
<!--      <%= render "likes/toppage_like", locals: { post: @post} %>-->
<!--    </div>-->
<!--  </div>-->
<!--  <% else %>-->
<!--    <div class="top_show_btn">-->
<!--     <%= link_to '戻る',root_path,class: "return_btn" %>-->
<!--    </div>-->
<!--  <% end %>-->
<!--</div>-->
<%
=end
%>