config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  resources :toppages, only: [:show]

  resources :users, only: [:show, :create, :edit, :update, :destroy, :destroy_confirm] do
   member do
     get :likes
   end
  end
  # post 'users/confirm', to: 'users#confirm'
  # patch 'users/edit/confirm/:id', to: 'users#edit_confirm'
  get 'users/delete/confirm/:id', to: 'users#destroy_confirm'
  
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :contracts, only: [:index, :create, :destroy, :update]
  # patch 'contracts/edit/confirm/:id', to: 'contracts#edit_confirm'
  
  resources :claims, only: [:new, :create, :destroy]
  get 'claims_list', to: 'claims#claims_list'
  
  namespace :admin do
    resources :info,only: [:show, :edit, :update]
    # patch 'info/edit/confirm/:id', to: 'info#edit_confirm'
  end
  
  resources :posts, only: [:new, :create, :index, :show, :destroy]
  # get 'posts/delete/confirm/:id', to: 'posts#destroy_confirm'

  resources :likes, only: [:create, :destroy, :index]
  
  resources :guest_sessions, only: [:create]
  
  resources :contacts, only: [:index, :create, :destroy]
  
  resources :comments, only: [:index, :create, :destroy]
  get 'comments/:id', to: 'comments#show'

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<div class="flash_msg">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<% if logged_in? && current_user.admin? %>
  <nav class="navbar navbar-expand-lg navbar-light">
    <i class="fas fa-leaf fa-3x fa_nav_color"></i>
    <%= link_to user_path(current_user.id) do %>
      <div class="login"><%= current_user.contractor_name %></div>
    <% end %>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#nav-bar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav-bar">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "トップページ","/", class: "menu_color" %>
        <li class="nav-item"><%= link_to "商品PR", posts_path,class: "menu_color" %></li>
        <li class="nav-item"><%= link_to "給付金請求一覧", claims_list_path,class: "menu_color" %></li>
        <li class="nav-item"><%= link_to "お問い合わせ一覧", comments_path,class: "menu_color" %></li>
        <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete,class: "menu_color"%></li>
      </ul>
    </div>
  </nav>
<% elsif  logged_in? %>
  <nav class="navbar navbar-expand-lg navbar-light">
    <i class="fas fa-leaf fa-3x fa_nav_color"></i>
    <%= link_to user_path(current_user.id) do %>
      <div class="login"><%= current_user.contractor_name %>さん</div>
    <% end %>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#nav-bar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav-bar">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "トップページ","/", class: "menu_color" %>
        <li class="nav-item"><%= link_to "ご契約一覧", contracts_path(current_user.id),class: "menu_color" %></li>
        <li class="nav-item"><%= link_to "請求のお手続き", new_claim_path(current_user.id),class: "menu_color" %></li>
        <li class="nav-item"><%= link_to "お気に入り", likes_path,class: "menu_color" %></li>
        <li class="nav-item"><%= link_to "お問い合わせ", contacts_path,class: "menu_color" %></li>
        <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete,class: "menu_color"%></li>
      </ul>
    </div>
  </nav>
<% else %>
  <nav class="navbar navbar-expand-lg navbar-light">
    <i class="fas fa-leaf fa-3x fa_nav_color"></i>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#nav-bar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav-bar">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "ご利用について","#link1", class: "menu_color" %>
        <li class="nav-item"><%= link_to "生命保険をご検討の方","#link2", class: "menu_color" %>
        <li class="nav-item"><%= link_to "よくある質問","#link3", class: "menu_color" %>
      </ul>
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Insurance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--vue.js-->
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>
    <!--bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <!--アイコン-->
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Abel&family=Kosugi+Maru&display=swap');
    </style>
    <!--スライドショー-->
    <link rel="stylesheet" type="text/css" href="css/slick.css"/>
    <script type="text/javascript" src="js/slick.min.js"></script>
  </head>
<body>
  <!--ローディング画面-->
  <div class="loading">
  	<div class="animation">少々お待ちください...</div>
  </div>
  <!--ページスクロールボタン-->
  <div class="top_btn">
    <i class="fas fa-arrow-alt-circle-up fa-3x fa_sp_color"></i>
  </div>

  <header>
    <div class="nav_wrapper">
      <%= render 'layouts/navbar' %>
    </div>
  </header>
  <div class="wrapper">
    <div class="flash_msg">
      <%= render 'layouts/flash_messages' %>
    </div>
    <%= yield %>
  </div>
  <footer>
    <small>&copy; 2021 WE ARE MUSCLE.</small>
  </footer>

</body>

</html>